version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "update-deps"  
    assignees:
      - "bmspd"
    reviewers:
      - "bmspd"
